jwt:
  secret: mysupercomplexsecret

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_management
    username: postgres
    password: 1234567890
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        globally_quoted_identifiers: true
        format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
  sql:
    init:
      mode: never
      continue-on-error: false
  main:
    web-application-type: servlet
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  codec:
    max-in-memory-size: 20MB
  profiles:
    active: @spring.profiles.active@
application:
  title: User Management
  version: 1.0
